Add a controller to auto gen KAC for a managed cluster.
stolostron/managedcluster-import-controller pull request #259
Opened 2023-07-24 03:16 UTC by xuezhaojun

2023-07-24 16:18 UTC, xuezhaojun commented
/hold

This PR require add klusterletaddonconfig permission in backplane-operator repo first.

2023-07-25 04:30 UTC, xuezhaojun commented
/test e2e

2023-07-25 06:19 UTC, xuezhaojun commented
/assign @qiujian16

2023-07-25 08:25 UTC, xuezhaojun commented
/assign @zhiweiyin318 
Hi, zhiwei, I need a approve tag on this one, please take a review when you have time, thanks!

2023-07-25 08:30 UTC, zhiweiyin318 commented
/approve

2023-07-25 08:38 UTC, xuezhaojun commented on pkg/controller/agentregistration/klusterletaddonconfig_controller_test.go
> +				Enabled: false,
Thanks for @zhiweiyin318  's explanation.

If you import a cluster from the console, the klustereletaddonconfig CR that the console generated set this field based on whether `search` component is enabled on the hub.

But in our case, util now, we set this to `false` for simplicity.

2023-07-25 08:49 UTC, zhiweiyin318 commented on pkg/controller/agentregistration/klusterletaddonconfig_controller.go
> +		if err = r.runtimeClient.Create(ctx, &klusterletaddonconfigv1.KlusterletAddonConfig{
agree with @zhujian7 's comment, we should move this part to klusterlet-addon-controller, because this is ACM API not MCE API.

2023-07-25 09:06 UTC, zhujian7 requested changes

2023-07-25 09:13 UTC, xuezhaojun commented on go.mod
> +	github.com/stolostron/klusterlet-addon-controller v0.0.0-20230705135736-ec14c0b2e548
Good idea. Let me implement this in klusterlet addon controller.

2023-07-25 10:08 UTC, xuezhaojun commented
Thanks for the reviews from @zhiweiyin318 and @zhujian7 , as they suggested, it's better to implement this feature in klusterlet-addon-controller: https://github.com/stolostron/klusterlet-addon-controller/pull/208

Their suggestions saved a lot of code and reduced the complexity in a great level! Great work!

2023-07-25 10:08 UTC, xuezhaojun commented
/close

2023-07-25 10:08 UTC, closed without merging